version: "3"
services:
  postgres:
    image: postgres:13
    container_name: "appdb"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 15432:5432